apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
  clusterIP: None  # This makes it a headless service, useful for connecting directly to the pod
